name: Request new matrix

description: Add metadata about a new matrix, including its hierarchy, translations, and key attributes.

title: Add matrix [X]

labels: [ New, Matrix ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new matrix request form!

        Please provide the necessary details about the matrix, including its unique identifier, name, description, and relevant hierarchy information.
  
  - type: input
    id: id
    attributes:
      label: Matrix ID
      description: Unique identifier for the matrix.
      placeholder: ex. peh:M001
    validations:
      required: true

  - type: input
    id: unique_name
    attributes:
      label: Unique Name
      description: A unique, human-readable name for the matrix.
      placeholder: ex. example_matrix
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      description: The official name of the matrix.
      placeholder: ex. Example Matrix
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the matrix.
    validations:
      required: false

  - type: input
    id: label
    attributes:
      label: Label
      description: A concise label for the matrix.
      placeholder: ex. Example Label
    validations:
      required: false

  - type: textarea
    id: remark
    attributes:
      label: Remark
      description: Any additional notes or remarks regarding the matrix.
    validations:
      required: false

  - type: input
    id: sort_order
    attributes:
      label: Sort Order
      description: The order in which the matrix should be sorted.
      placeholder: ex. 1
    validations:
      required: false

  - type: input
    id: aggregation_target
    attributes:
      label: Aggregation Target
      description: The primary target for aggregation.
      placeholder: ex. Target X
    validations:
      required: false

  - type: input
    id: parent_matrix
    attributes:
      label: Parent Matrix
      description: Specify the parent matrix if applicable.
      placeholder: ex. ParentMatrixX
    validations:
      required: false

  - type: textarea
    id: secondary_parent_matrix_id_list
    attributes:
      label: Secondary Parent Matrices
      description: List any secondary parent matrices (comma-separated).
      placeholder: ex. ParentMatrixY, ParentMatrixZ
    validations:
      required: false

  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: |
        Provide translations as a list in the format:
        ```
        - property_name: example_property
          language: en
          translated_value: Example Translation
        - property_name: another_property
          language: fr
          translated_value: Traduction Exemple
        ```
      placeholder: |
        - property_name: matrix_property
          language: en
          translated_value: Example Translation
    validations:
      required: false
