name: Publish Vocabulary

permissions:
  contents: write

on:
    release:
        types: [published]


jobs:
    publish-vocabulary:
        if: github.repository != 'eu-parc/vocabulary-template'
        uses: eu-parc/voc2skosmos-workflow/.github/workflows/yml2skos.yml@main
        with:
            ref: ${{ github.ref }}
            namespace: https://w3id.org/peh/terms/
            namespace_label: pehterms
            linkml_schema: https://raw.githubusercontent.com/eu-parc/parco-hbm/main/linkml/schema/peh.yaml
            data: data/data.yaml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}